/*

Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

function countEvenFibonacciNumbers() {
  var termA = 0;
  var termB = 1;
  var sumOfEvenTerms = 0;

  while (termA + termB < 4000000) {
    var newTerm = 0;
    newTerm = termA + termB;
    termA = termB;
    termB = newTerm;
    if (newTerm % 2 === 0) {
      sumOfEvenTerms += newTerm;
    }
    console.log("Current term: " + newTerm + ", sum of even terms: " + sumOfEvenTerms);
  }
}

countEvenFibonacciNumbers();